First commit
Moses-chibuike/Project-Review pull request #1
Opened 2023-01-16 11:48 UTC by Moses-chibuike

-  add styles to the page's image tag
-  add listed section of the page
-  add notes and acknowledgement in the README.md file

2023-01-16 15:08 UTC, Moses-chibuike reviewed
# Changes Required ♻️

Good job so far! 👍 
There are some issues that you still need to work on to go to the next project but you are almost there!

2023-01-16 15:08 UTC, Moses-chibuike commented on index.html
> +      </div>
Why don't you add required to the Textarea field, so a user won't have to send an empty message

2023-01-16 15:08 UTC, Moses-chibuike commented on index.html
> +    -->
As this is a precoding instruction kindly remove it to make your code neater

2023-01-16 15:34 UTC, osamaashraf6 requested changes
Hi @Moses-chibuike 😊, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![SoCloseAlmostGIF](https://user-images.githubusercontent.com/83360636/212714978-630d9e3b-99a6-4cc6-a1db-6b66415c7202.gif)

## Highlights👍

- [ ] Great job at using the inline comments💯

## Required Changes ♻️


_Check the comments under the review._

## Optional suggestions
- [ ] Try to mention the name of the student up the review and the  Highlights👍for the student to make him/her feel that he/she did well on the project😃 , please take a look at mine here to understand I mentioned here the Highlights for you after that I mentioned the  Required Changes ♻️, so you will achieve GitHub features for reviews😊


_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-16 15:34 UTC, osamaashraf6 commented on index.html
> +      </div>
> Why don't you add required to the Textarea field, so a user won't have to send an empty message

- [ ] Great job 😃at adding the inline comments, but I see you ask the student a direct question😊 and you are looking strict, so kindly instead of that you can tell the students at first :
```Great job 💪 at adding the textarea, but there are some issues you want to work on, kindly 😊try to put the required validation, so the users can not send empty data```💯 
, so try to be polite 😊at the review to be friendly with the students you can also use other sentences like 
``` it will be better or I suggest or kindly```, so after that you will achieve the GitHub features for review.👌

2023-01-16 16:04 UTC, Moses-chibuike reviewed
# Changes Required ♻️

Good job so far! 👍

There are some issues that you still need to work on to go to the next project but you are almost there!😊

2023-01-16 16:04 UTC, Moses-chibuike commented on index.html
> +      </div>
Good job 💪 at adding the textarea, but there are some issues you have to work on, 😊Please try to put the required validation, so the users can not send empty data

2023-01-16 16:14 UTC, christianbiring1 reviewed
Hi @Moses-chibuike , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
# STATUS: APPROVED :tada: 
![imageswelljob](https://user-images.githubusercontent.com/97100091/212723297-13cf3825-ebd9-4d09-8670-fe14c57218ec.jpeg)

## Highlights
- [ ] the comments are given in a polite and friendly manner :+1: 
- [ ] Use of github review changes feature :+1: 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-16 09:43 UTC, merged

2023-04-16 10:10 UTC, Moses-chibuike commented on index.html
> +      </div>
Thanks @osamaashraf6 , This was really helpful.

2023-04-16 10:14 UTC, Moses-chibuike commented
Thanks for the swift reply @christianbiring1